apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrYTJseWFXeHNPbWRvY0Y4M1pqVkxVMjFNTjFoS2VEZzRkRGRrTm5oRE16ZHhTR3RGWW1KRVZGYzBaR2N5VUVZPSIKCQl9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=

type: kubernetes.io/dockerconfigjson
