apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICIwSnZRbnRDVDBKalFuVUZ1WkV0cFVtbE1URHBuYUhCZlFuVTVRbE5rTVdkcGFIVmpZWEZEWVVKNFdsRjZWRXhpV1djemFGTTFNVUpTVlVoRCIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
